[2025-06-30T17:47:58.319+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:47:58.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:47:58.326+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:47:58.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:47:58.332+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:47:58.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:47:58.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:47:58.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.064 seconds
[2025-06-30T17:48:28.544+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:48:28.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:48:28.554+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:48:28.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:48:28.565+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:48:28.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:48:28.566+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:48:28.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.079 seconds
[2025-06-30T17:48:59.248+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:48:59.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:48:59.257+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:48:59.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:48:59.261+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:48:59.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:48:59.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:48:59.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.041 seconds
[2025-06-30T17:49:29.476+0000] {processor.py:186} INFO - Started process (PID=247) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:49:29.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:49:29.480+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:49:29.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:49:29.484+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:49:29.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:49:29.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:49:29.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.036 seconds
[2025-06-30T17:49:59.781+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:49:59.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:49:59.786+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:49:59.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:49:59.790+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:49:59.789+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:49:59.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:49:59.812+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.040 seconds
[2025-06-30T17:50:29.902+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:50:29.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:50:29.913+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:50:29.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:50:29.918+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:50:29.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:50:29.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:50:29.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.051 seconds
[2025-06-30T17:51:00.193+0000] {processor.py:186} INFO - Started process (PID=436) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:51:00.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:51:00.202+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:51:00.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:51:00.206+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:51:00.205+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:51:00.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:51:00.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.041 seconds
[2025-06-30T17:51:30.501+0000] {processor.py:186} INFO - Started process (PID=499) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:51:30.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:51:30.506+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:51:30.505+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:51:30.512+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:51:30.509+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:51:30.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:51:30.544+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.053 seconds
[2025-06-30T17:52:00.678+0000] {processor.py:186} INFO - Started process (PID=568) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:52:00.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:52:00.688+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:52:00.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:52:00.692+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:52:00.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:52:00.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:52:00.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.054 seconds
[2025-06-30T17:52:31.251+0000] {processor.py:186} INFO - Started process (PID=631) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:52:31.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:52:31.254+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:52:31.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:52:31.259+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:52:31.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:52:31.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:52:31.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.039 seconds
[2025-06-30T17:53:01.549+0000] {processor.py:186} INFO - Started process (PID=694) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:53:01.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:53:01.558+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:53:01.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:53:01.562+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:53:01.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:53:01.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:53:01.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.044 seconds
[2025-06-30T17:53:31.996+0000] {processor.py:186} INFO - Started process (PID=757) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:53:32.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:53:32.005+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:53:32.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:53:32.010+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:53:32.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:53:32.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:53:32.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.046 seconds
[2025-06-30T17:54:02.463+0000] {processor.py:186} INFO - Started process (PID=820) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:54:02.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:54:02.473+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:54:02.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:54:02.477+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:54:02.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:54:02.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:54:02.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.042 seconds
[2025-06-30T17:54:32.725+0000] {processor.py:186} INFO - Started process (PID=883) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:54:32.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:54:32.735+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:54:32.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:54:32.741+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:54:32.739+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:54:32.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:54:32.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.051 seconds
[2025-06-30T17:55:03.104+0000] {processor.py:186} INFO - Started process (PID=946) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:55:03.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:55:03.115+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:55:03.114+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:55:03.119+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:55:03.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:55:03.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:55:03.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.055 seconds
[2025-06-30T17:55:33.542+0000] {processor.py:186} INFO - Started process (PID=1009) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:55:33.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:55:33.552+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:55:33.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:55:33.556+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:55:33.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:55:33.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:55:33.590+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.056 seconds
[2025-06-30T17:56:03.807+0000] {processor.py:186} INFO - Started process (PID=1072) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:56:03.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:56:03.816+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:56:03.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:56:03.820+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:56:03.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:56:03.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:56:03.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.052 seconds
[2025-06-30T17:56:34.380+0000] {processor.py:186} INFO - Started process (PID=1135) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:56:34.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:56:34.385+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:56:34.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:56:34.392+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:56:34.391+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:56:34.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:56:34.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.058 seconds
[2025-06-30T17:57:04.533+0000] {processor.py:186} INFO - Started process (PID=1198) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:57:04.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:57:04.543+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:57:04.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:57:04.547+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:57:04.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:57:04.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:57:04.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.048 seconds
[2025-06-30T17:57:35.035+0000] {processor.py:186} INFO - Started process (PID=1261) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:57:35.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:57:35.052+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:57:35.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:57:35.064+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:57:35.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:57:35.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:57:35.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.102 seconds
[2025-06-30T17:58:05.321+0000] {processor.py:186} INFO - Started process (PID=1324) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:58:05.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:58:05.330+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:58:05.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:58:05.334+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:58:05.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:58:05.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:58:05.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.047 seconds
[2025-06-30T17:58:35.819+0000] {processor.py:186} INFO - Started process (PID=1387) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:58:35.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:58:35.833+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:58:35.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:58:35.844+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:58:35.840+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:58:35.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:58:35.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.106 seconds
[2025-06-30T17:59:06.267+0000] {processor.py:186} INFO - Started process (PID=1450) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:59:06.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:59:06.273+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:59:06.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:59:06.278+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:59:06.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:59:06.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:59:06.311+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.055 seconds
[2025-06-30T17:59:37.038+0000] {processor.py:186} INFO - Started process (PID=1513) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:59:37.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T17:59:37.052+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:59:37.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:59:37.059+0000] {logging_mixin.py:190} INFO - [2025-06-30T17:59:37.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T17:59:37.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T17:59:37.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.064 seconds
[2025-06-30T18:00:07.183+0000] {processor.py:186} INFO - Started process (PID=1576) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:00:07.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:00:07.187+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:00:07.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:00:07.190+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:00:07.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:00:07.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:00:07.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.037 seconds
[2025-06-30T18:00:37.371+0000] {processor.py:186} INFO - Started process (PID=1639) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:00:37.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:00:37.380+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:00:37.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:00:37.384+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:00:37.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:00:37.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:00:37.413+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.053 seconds
[2025-06-30T18:01:07.649+0000] {processor.py:186} INFO - Started process (PID=1701) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:01:07.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:01:07.659+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:01:07.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:01:07.663+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:01:07.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:01:07.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:01:07.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.043 seconds
[2025-06-30T18:01:38.222+0000] {processor.py:186} INFO - Started process (PID=1764) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:01:38.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:01:38.233+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:01:38.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:01:38.238+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:01:38.237+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:01:38.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:01:38.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.060 seconds
[2025-06-30T18:02:08.690+0000] {processor.py:186} INFO - Started process (PID=1827) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:02:08.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:02:08.700+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:02:08.700+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:02:08.704+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:02:08.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:02:08.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:02:08.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.054 seconds
[2025-06-30T18:02:39.131+0000] {processor.py:186} INFO - Started process (PID=1890) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:02:39.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:02:39.142+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:02:39.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:02:39.148+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:02:39.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:02:39.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:02:39.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.059 seconds
[2025-06-30T18:03:09.524+0000] {processor.py:186} INFO - Started process (PID=1953) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:03:09.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:03:09.536+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:03:09.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:03:09.543+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:03:09.541+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:03:09.544+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:03:09.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.060 seconds
[2025-06-30T18:03:40.106+0000] {processor.py:186} INFO - Started process (PID=2016) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:03:40.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:03:40.116+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:03:40.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:03:40.121+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:03:40.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:03:40.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:03:40.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.046 seconds
[2025-06-30T18:04:10.660+0000] {processor.py:186} INFO - Started process (PID=2079) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:04:10.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:04:10.677+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:04:10.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:04:10.687+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:04:10.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:04:10.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:04:10.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.063 seconds
[2025-06-30T18:04:40.906+0000] {processor.py:186} INFO - Started process (PID=2142) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:04:40.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:04:40.910+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:04:40.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:04:40.913+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:04:40.912+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:04:40.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:04:40.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.033 seconds
[2025-06-30T18:05:11.213+0000] {processor.py:186} INFO - Started process (PID=2204) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:05:11.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:05:11.222+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:05:11.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:05:11.226+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:05:11.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:05:11.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:05:11.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.043 seconds
[2025-06-30T18:05:42.274+0000] {processor.py:186} INFO - Started process (PID=2267) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:05:42.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:05:42.284+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:05:42.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:05:42.288+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:05:42.287+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:05:42.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:05:42.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.045 seconds
[2025-06-30T18:06:12.811+0000] {processor.py:186} INFO - Started process (PID=2330) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:06:12.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:06:12.815+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:06:12.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:06:12.819+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:06:12.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:06:12.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:06:12.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.041 seconds
[2025-06-30T18:06:42.936+0000] {processor.py:186} INFO - Started process (PID=2393) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:06:42.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:06:42.945+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:06:42.945+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:06:42.949+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:06:42.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:06:42.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:06:42.971+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.041 seconds
[2025-06-30T18:07:13.877+0000] {processor.py:186} INFO - Started process (PID=2456) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:07:13.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:07:13.883+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:07:13.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:07:13.892+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:07:13.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:07:13.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:07:13.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.062 seconds
[2025-06-30T18:07:44.325+0000] {processor.py:186} INFO - Started process (PID=2519) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:07:44.333+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:07:44.341+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:07:44.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:07:44.352+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:07:44.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:07:44.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:07:44.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.070 seconds
[2025-06-30T18:08:14.777+0000] {processor.py:186} INFO - Started process (PID=2582) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:08:14.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:08:14.781+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:08:14.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:08:14.785+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:08:14.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:08:14.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:08:14.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.039 seconds
[2025-06-30T18:08:44.899+0000] {processor.py:186} INFO - Started process (PID=2645) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:08:44.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:08:44.902+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:08:44.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:08:44.906+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:08:44.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:08:44.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:08:44.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.039 seconds
[2025-06-30T18:09:15.639+0000] {processor.py:186} INFO - Started process (PID=2701) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:09:15.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:09:15.649+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:09:15.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:09:15.653+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:09:15.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:09:15.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:09:15.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.055 seconds
[2025-06-30T18:09:45.788+0000] {processor.py:186} INFO - Started process (PID=2763) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:09:45.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:09:45.792+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:09:45.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:09:45.797+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:09:45.795+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:09:45.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:09:45.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.037 seconds
[2025-06-30T18:10:16.614+0000] {processor.py:186} INFO - Started process (PID=2823) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:10:16.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:10:16.625+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:10:16.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:10:16.630+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:10:16.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:10:16.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:10:16.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.063 seconds
[2025-06-30T18:10:46.855+0000] {processor.py:186} INFO - Started process (PID=2886) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:10:46.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:10:46.870+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:10:46.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:10:46.876+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:10:46.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:10:46.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:10:46.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.055 seconds
[2025-06-30T18:11:17.311+0000] {processor.py:186} INFO - Started process (PID=2949) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:11:17.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:11:17.323+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:11:17.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:11:17.329+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:11:17.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:11:17.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:11:17.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.058 seconds
[2025-06-30T18:11:47.774+0000] {processor.py:186} INFO - Started process (PID=3012) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:11:47.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:11:47.778+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:11:47.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:11:47.784+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:11:47.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:11:47.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:11:47.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.043 seconds
[2025-06-30T18:12:18.325+0000] {processor.py:186} INFO - Started process (PID=3075) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:12:18.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:12:18.342+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:12:18.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:12:18.354+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:12:18.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:12:18.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:12:18.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.079 seconds
[2025-06-30T18:12:48.911+0000] {processor.py:186} INFO - Started process (PID=3137) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:12:48.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:12:48.922+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:12:48.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:12:48.928+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:12:48.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:12:48.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:12:48.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.054 seconds
[2025-06-30T18:13:19.414+0000] {processor.py:186} INFO - Started process (PID=3200) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:13:19.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:13:19.424+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:13:19.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:13:19.428+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:13:19.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:13:19.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:13:19.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.046 seconds
[2025-06-30T18:13:49.679+0000] {processor.py:186} INFO - Started process (PID=3263) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:13:49.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:13:49.683+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:13:49.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:13:49.687+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:13:49.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:13:49.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:13:49.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.044 seconds
[2025-06-30T18:14:19.809+0000] {processor.py:186} INFO - Started process (PID=3325) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:14:19.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:14:19.812+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:14:19.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:14:19.816+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:14:19.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:14:19.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:14:19.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.037 seconds
[2025-06-30T18:14:50.787+0000] {processor.py:186} INFO - Started process (PID=3388) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:14:50.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:14:50.800+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:14:50.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:14:50.810+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:14:50.806+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:14:50.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:14:50.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.071 seconds
[2025-06-30T18:15:21.117+0000] {processor.py:186} INFO - Started process (PID=3450) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:15:21.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:15:21.128+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:15:21.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:15:21.134+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:15:21.132+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:15:21.135+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:15:21.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.058 seconds
[2025-06-30T18:15:52.080+0000] {processor.py:186} INFO - Started process (PID=3513) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:15:52.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:15:52.089+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:15:52.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:15:52.093+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:15:52.092+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:15:52.094+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:15:52.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.046 seconds
[2025-06-30T18:16:22.854+0000] {processor.py:186} INFO - Started process (PID=3576) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:16:22.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:16:22.864+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:16:22.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:16:22.869+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:16:22.867+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:16:22.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:16:22.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.053 seconds
[2025-06-30T18:16:53.019+0000] {processor.py:186} INFO - Started process (PID=3639) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:16:53.020+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:16:53.024+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:16:53.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:16:53.030+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:16:53.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:16:53.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:16:53.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.049 seconds
[2025-06-30T18:17:23.436+0000] {processor.py:186} INFO - Started process (PID=3702) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:17:23.443+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:17:23.447+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:17:23.447+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:17:23.453+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:17:23.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:17:23.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:17:23.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.056 seconds
[2025-06-30T18:17:54.081+0000] {processor.py:186} INFO - Started process (PID=3765) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:17:54.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:17:54.090+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:17:54.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:17:54.094+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:17:54.093+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:17:54.095+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:17:54.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.047 seconds
[2025-06-30T18:18:24.617+0000] {processor.py:186} INFO - Started process (PID=3828) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:18:24.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:18:24.627+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:18:24.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:18:24.631+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:18:24.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:18:24.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:18:24.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.048 seconds
[2025-06-30T18:18:55.136+0000] {processor.py:186} INFO - Started process (PID=3891) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:18:55.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:18:55.147+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:18:55.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:18:55.152+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:18:55.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:18:55.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:18:55.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.053 seconds
[2025-06-30T18:19:26.148+0000] {processor.py:186} INFO - Started process (PID=3954) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:19:26.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:19:26.153+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:19:26.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:19:26.160+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:19:26.158+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:19:26.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:19:26.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.121 seconds
[2025-06-30T18:19:56.910+0000] {processor.py:186} INFO - Started process (PID=4017) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:19:56.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:19:56.915+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:19:56.914+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:19:56.921+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:19:56.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:19:56.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:19:56.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.043 seconds
[2025-06-30T18:20:27.765+0000] {processor.py:186} INFO - Started process (PID=4080) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:20:27.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:20:27.775+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:20:27.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:20:27.779+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:20:27.778+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:20:27.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:20:27.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.049 seconds
[2025-06-30T18:20:57.958+0000] {processor.py:186} INFO - Started process (PID=4143) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:20:57.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:20:57.976+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:20:57.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:20:57.986+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:20:57.984+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:20:57.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:20:58.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.073 seconds
[2025-06-30T18:21:28.105+0000] {processor.py:186} INFO - Started process (PID=4206) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:21:28.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:21:28.108+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:21:28.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:21:28.112+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:21:28.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:21:28.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:21:28.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.038 seconds
[2025-06-30T18:21:58.300+0000] {processor.py:186} INFO - Started process (PID=4269) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:21:58.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:21:58.310+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:21:58.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:21:58.314+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:21:58.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:21:58.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:21:58.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.044 seconds
[2025-06-30T18:22:28.983+0000] {processor.py:186} INFO - Started process (PID=4332) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:22:28.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:22:28.988+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:22:28.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:22:28.993+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:22:28.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:22:28.993+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:22:29.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.051 seconds
[2025-06-30T18:22:59.154+0000] {processor.py:186} INFO - Started process (PID=4395) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:22:59.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:22:59.174+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:22:59.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:22:59.188+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:22:59.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:22:59.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:22:59.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.112 seconds
[2025-06-30T18:23:29.598+0000] {processor.py:186} INFO - Started process (PID=4458) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:23:29.599+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:23:29.603+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:23:29.602+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:23:29.608+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:23:29.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:23:29.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:23:29.632+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.042 seconds
[2025-06-30T18:24:00.212+0000] {processor.py:186} INFO - Started process (PID=4521) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:24:00.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:24:00.219+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:24:00.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:24:00.226+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:24:00.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:24:00.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:24:00.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.076 seconds
[2025-06-30T18:24:30.914+0000] {processor.py:186} INFO - Started process (PID=4584) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:24:30.922+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:24:30.925+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:24:30.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:24:30.929+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:24:30.928+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:24:30.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:24:30.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.053 seconds
[2025-06-30T18:25:01.197+0000] {processor.py:186} INFO - Started process (PID=4646) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:25:01.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:25:01.207+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:25:01.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:25:01.212+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:25:01.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:25:01.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:25:01.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.054 seconds
[2025-06-30T18:25:32.042+0000] {processor.py:186} INFO - Started process (PID=4709) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:25:32.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:25:32.054+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:25:32.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:25:32.061+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:25:32.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:25:32.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:25:32.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.063 seconds
[2025-06-30T18:26:02.554+0000] {processor.py:186} INFO - Started process (PID=4772) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:26:02.561+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:26:02.564+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:26:02.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:26:02.569+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:26:02.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:26:02.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:26:02.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.061 seconds
[2025-06-30T18:26:33.328+0000] {processor.py:186} INFO - Started process (PID=4835) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:26:33.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:26:33.333+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:26:33.332+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:26:33.337+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:26:33.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:26:33.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:26:33.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.050 seconds
[2025-06-30T18:27:04.042+0000] {processor.py:186} INFO - Started process (PID=4898) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:27:04.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:27:04.051+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:27:04.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:27:04.055+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:27:04.054+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:27:04.056+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:27:04.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.049 seconds
[2025-06-30T18:27:34.874+0000] {processor.py:186} INFO - Started process (PID=4961) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:27:34.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:27:34.884+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:27:34.884+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:27:34.890+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:27:34.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:27:34.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:27:34.919+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.058 seconds
[2025-06-30T18:28:05.017+0000] {processor.py:186} INFO - Started process (PID=5024) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:28:05.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:28:05.031+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:28:05.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:28:05.037+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:28:05.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:28:05.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:28:05.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.091 seconds
[2025-06-30T18:28:35.642+0000] {processor.py:186} INFO - Started process (PID=5087) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:28:35.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:28:35.652+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:28:35.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:28:35.658+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:28:35.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:28:35.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:28:35.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.050 seconds
[2025-06-30T18:29:05.953+0000] {processor.py:186} INFO - Started process (PID=5150) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:29:05.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:29:05.963+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:29:05.963+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:29:05.968+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:29:05.967+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:29:05.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:29:05.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.052 seconds
[2025-06-30T18:29:36.841+0000] {processor.py:186} INFO - Started process (PID=5213) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:29:36.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:29:36.851+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:29:36.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:29:36.854+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:29:36.853+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:29:36.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:29:36.876+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.044 seconds
[2025-06-30T18:30:07.284+0000] {processor.py:186} INFO - Started process (PID=5276) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:30:07.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:30:07.287+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:30:07.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:30:07.291+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:30:07.290+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:30:07.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:30:07.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.039 seconds
[2025-06-30T18:30:37.904+0000] {processor.py:186} INFO - Started process (PID=5339) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:30:37.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:30:37.913+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:30:37.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:30:37.917+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:30:37.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:30:37.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:30:37.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.045 seconds
[2025-06-30T18:31:08.389+0000] {processor.py:186} INFO - Started process (PID=5402) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:31:08.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:31:08.393+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:31:08.393+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:31:08.397+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:31:08.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:31:08.398+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:31:08.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.039 seconds
[2025-06-30T18:31:39.091+0000] {processor.py:186} INFO - Started process (PID=5465) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:31:39.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:31:39.094+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:31:39.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:31:39.098+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:31:39.097+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:31:39.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:31:39.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.043 seconds
[2025-06-30T18:32:09.458+0000] {processor.py:186} INFO - Started process (PID=5529) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:32:09.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:32:09.464+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:32:09.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:32:09.470+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:32:09.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:32:09.471+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:32:09.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.062 seconds
[2025-06-30T18:32:39.601+0000] {processor.py:186} INFO - Started process (PID=5582) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:32:39.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:32:39.606+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:32:39.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:32:39.611+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:32:39.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:32:39.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:32:39.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.052 seconds
[2025-06-30T18:33:10.098+0000] {processor.py:186} INFO - Started process (PID=5645) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:33:10.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:33:10.109+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:33:10.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:33:10.116+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:33:10.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:33:10.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:33:10.144+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.055 seconds
[2025-06-30T18:33:40.748+0000] {processor.py:186} INFO - Started process (PID=5714) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:33:40.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:33:40.758+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:33:40.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:33:40.762+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:33:40.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:33:40.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:33:40.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.056 seconds
[2025-06-30T18:34:11.580+0000] {processor.py:186} INFO - Started process (PID=5777) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:34:11.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:34:11.598+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:34:11.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:34:11.607+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:34:11.604+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:34:11.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:34:11.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.087 seconds
[2025-06-30T18:34:42.317+0000] {processor.py:186} INFO - Started process (PID=5840) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:34:42.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:34:42.327+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:34:42.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:34:42.331+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:34:42.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:34:42.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:34:42.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.050 seconds
[2025-06-30T18:35:13.041+0000] {processor.py:186} INFO - Started process (PID=5903) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:35:13.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:35:13.045+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:35:13.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:35:13.050+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:35:13.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:35:13.050+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:35:13.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.037 seconds
[2025-06-30T18:35:43.442+0000] {processor.py:186} INFO - Started process (PID=5966) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:35:43.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:35:43.452+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:35:43.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:35:43.456+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:35:43.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:35:43.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:35:43.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.050 seconds
[2025-06-30T18:36:13.837+0000] {processor.py:186} INFO - Started process (PID=6029) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:36:13.844+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:36:13.847+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:36:13.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:36:13.851+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:36:13.850+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:36:13.851+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:36:13.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.043 seconds
[2025-06-30T18:36:44.281+0000] {processor.py:186} INFO - Started process (PID=6092) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:36:44.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:36:44.291+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:36:44.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:36:44.295+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:36:44.293+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:36:44.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:36:44.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.049 seconds
[2025-06-30T18:37:14.748+0000] {processor.py:186} INFO - Started process (PID=6154) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:37:14.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T18:37:14.759+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:37:14.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:37:14.764+0000] {logging_mixin.py:190} INFO - [2025-06-30T18:37:14.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T18:37:14.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T18:37:14.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.044 seconds
[2025-06-30T19:51:17.855+0000] {processor.py:186} INFO - Started process (PID=6210) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T19:51:17.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-30T19:51:17.892+0000] {logging_mixin.py:190} INFO - [2025-06-30T19:51:17.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T19:51:17.916+0000] {logging_mixin.py:190} INFO - [2025-06-30T19:51:17.914+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-30T19:51:17.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-30T19:51:18.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.337 seconds
