[2025-07-01T17:20:56.974+0000] {processor.py:186} INFO - Started process (PID=6272) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T17:20:56.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T17:20:57.027+0000] {logging_mixin.py:190} INFO - [2025-07-01T17:20:57.026+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T17:20:57.053+0000] {logging_mixin.py:190} INFO - [2025-07-01T17:20:57.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T17:20:57.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T17:20:57.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.246 seconds
[2025-07-01T21:05:53.791+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:05:53.792+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:05:53.797+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:05:53.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:05:53.805+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:05:53.802+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:05:53.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:05:53.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.083 seconds
[2025-07-01T21:06:24.366+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:06:24.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:06:24.375+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:06:24.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:06:24.379+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:06:24.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:06:24.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:06:24.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.041 seconds
[2025-07-01T21:06:54.907+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:06:54.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:06:54.911+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:06:54.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:06:54.916+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:06:54.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:06:54.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:06:54.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.073 seconds
[2025-07-01T21:07:25.304+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:07:25.306+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:07:25.310+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:07:25.309+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:07:25.316+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:07:25.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:07:25.318+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:07:25.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.058 seconds
[2025-07-01T21:07:55.426+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:07:55.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:07:55.437+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:07:55.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:07:55.453+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:07:55.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:07:55.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:07:55.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.088 seconds
[2025-07-01T21:08:26.178+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:08:26.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:08:26.189+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:08:26.188+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:08:26.193+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:08:26.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:08:26.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:08:26.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.045 seconds
[2025-07-01T21:08:57.061+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:08:57.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:08:57.071+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:08:57.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:08:57.076+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:08:57.075+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:08:57.077+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:08:57.096+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.045 seconds
[2025-07-01T21:09:27.641+0000] {processor.py:186} INFO - Started process (PID=501) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:09:27.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:09:27.650+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:09:27.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:09:27.654+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:09:27.653+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:09:27.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:09:27.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.043 seconds
[2025-07-01T21:09:58.636+0000] {processor.py:186} INFO - Started process (PID=564) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:09:58.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:09:58.650+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:09:58.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:09:58.658+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:09:58.655+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:09:58.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:09:58.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.070 seconds
[2025-07-01T21:10:29.205+0000] {processor.py:186} INFO - Started process (PID=627) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:10:29.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:10:29.216+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:10:29.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:10:29.221+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:10:29.219+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:10:29.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:10:29.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.064 seconds
[2025-07-01T21:10:59.913+0000] {processor.py:186} INFO - Started process (PID=690) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:10:59.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:10:59.923+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:10:59.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:10:59.928+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:10:59.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:10:59.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:10:59.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.044 seconds
[2025-07-01T21:11:30.679+0000] {processor.py:186} INFO - Started process (PID=753) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:11:30.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:11:30.689+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:11:30.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:11:30.692+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:11:30.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:11:30.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:11:30.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.044 seconds
[2025-07-01T21:12:01.321+0000] {processor.py:186} INFO - Started process (PID=816) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:12:01.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:12:01.331+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:12:01.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:12:01.335+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:12:01.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:12:01.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:12:01.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.044 seconds
[2025-07-01T21:12:32.066+0000] {processor.py:186} INFO - Started process (PID=879) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:12:32.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:12:32.070+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:12:32.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:12:32.074+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:12:32.073+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:12:32.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:12:32.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.037 seconds
[2025-07-01T21:13:02.631+0000] {processor.py:186} INFO - Started process (PID=942) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:13:02.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:13:02.636+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:13:02.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:13:02.641+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:13:02.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:13:02.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:13:02.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.048 seconds
[2025-07-01T21:13:33.451+0000] {processor.py:186} INFO - Started process (PID=1005) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:13:33.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:13:33.458+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:13:33.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:13:33.463+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:13:33.462+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:13:33.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:13:33.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.060 seconds
[2025-07-01T21:14:03.618+0000] {processor.py:186} INFO - Started process (PID=1068) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:14:03.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:14:03.623+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:14:03.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:14:03.629+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:14:03.627+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:14:03.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:14:03.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.056 seconds
[2025-07-01T21:14:33.930+0000] {processor.py:186} INFO - Started process (PID=1131) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:14:33.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:14:33.941+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:14:33.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:14:33.945+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:14:33.944+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:14:33.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:14:33.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.056 seconds
[2025-07-01T21:15:04.195+0000] {processor.py:186} INFO - Started process (PID=1194) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:15:04.202+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:15:04.205+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:15:04.204+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:15:04.209+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:15:04.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:15:04.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:15:04.233+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.046 seconds
[2025-07-01T21:15:34.392+0000] {processor.py:186} INFO - Started process (PID=1257) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:15:34.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:15:34.398+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:15:34.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:15:34.406+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:15:34.404+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:15:34.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:15:34.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.053 seconds
[2025-07-01T21:16:04.678+0000] {processor.py:186} INFO - Started process (PID=1320) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:16:04.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:16:04.696+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:16:04.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:16:04.708+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:16:04.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:16:04.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:16:04.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.120 seconds
[2025-07-01T21:16:35.503+0000] {processor.py:186} INFO - Started process (PID=1383) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:16:35.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:16:35.513+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:16:35.513+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:16:35.518+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:16:35.516+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:16:35.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:16:35.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.051 seconds
[2025-07-01T21:17:05.857+0000] {processor.py:186} INFO - Started process (PID=1446) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:17:05.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:17:05.861+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:17:05.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:17:05.864+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:17:05.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:17:05.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:17:05.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.041 seconds
[2025-07-01T21:17:36.019+0000] {processor.py:186} INFO - Started process (PID=1509) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:17:36.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:17:36.029+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:17:36.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:17:36.033+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:17:36.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:17:36.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:17:36.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.044 seconds
[2025-07-01T21:18:06.432+0000] {processor.py:186} INFO - Started process (PID=1572) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:18:06.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:18:06.437+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:18:06.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:18:06.443+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:18:06.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:18:06.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:18:06.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.049 seconds
[2025-07-01T21:18:37.068+0000] {processor.py:186} INFO - Started process (PID=1635) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:18:37.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:18:37.079+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:18:37.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:18:37.084+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:18:37.082+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:18:37.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:18:37.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.050 seconds
[2025-07-01T21:19:07.412+0000] {processor.py:186} INFO - Started process (PID=1698) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:19:07.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:19:07.428+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:19:07.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:19:07.438+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:19:07.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:19:07.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:19:07.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.080 seconds
[2025-07-01T21:19:37.767+0000] {processor.py:186} INFO - Started process (PID=1761) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:19:37.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:19:37.771+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:19:37.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:19:37.775+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:19:37.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:19:37.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:19:37.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.038 seconds
[2025-07-01T21:20:08.648+0000] {processor.py:186} INFO - Started process (PID=1824) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:20:08.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:20:08.658+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:20:08.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:20:08.662+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:20:08.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:20:08.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:20:08.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.046 seconds
[2025-07-01T21:20:38.750+0000] {processor.py:186} INFO - Started process (PID=1887) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:20:38.751+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:20:38.755+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:20:38.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:20:38.761+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:20:38.759+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:20:38.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:20:38.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.054 seconds
[2025-07-01T21:21:08.924+0000] {processor.py:186} INFO - Started process (PID=1949) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:21:08.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:21:08.935+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:21:08.934+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:21:08.939+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:21:08.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:21:08.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:21:08.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.053 seconds
[2025-07-01T21:21:39.322+0000] {processor.py:186} INFO - Started process (PID=2012) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:21:39.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:21:39.327+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:21:39.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:21:39.334+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:21:39.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:21:39.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:21:39.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.062 seconds
[2025-07-01T21:22:09.625+0000] {processor.py:186} INFO - Started process (PID=2075) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:22:09.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:22:09.636+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:22:09.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:22:09.641+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:22:09.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:22:09.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:22:09.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.052 seconds
[2025-07-01T21:22:39.718+0000] {processor.py:186} INFO - Started process (PID=2138) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:22:39.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:22:39.728+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:22:39.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:22:39.732+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:22:39.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:22:39.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:22:39.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.045 seconds
[2025-07-01T21:23:10.290+0000] {processor.py:186} INFO - Started process (PID=2201) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:23:10.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:23:10.304+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:23:10.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:23:10.308+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:23:10.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:23:10.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:23:10.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.063 seconds
[2025-07-01T21:23:40.784+0000] {processor.py:186} INFO - Started process (PID=2264) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:23:40.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:23:40.792+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:23:40.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:23:40.799+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:23:40.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:23:40.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:23:40.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.058 seconds
[2025-07-01T21:24:11.271+0000] {processor.py:186} INFO - Started process (PID=2327) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:24:11.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-07-01T21:24:11.281+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:24:11.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:24:11.285+0000] {logging_mixin.py:190} INFO - [2025-07-01T21:24:11.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-07-01T21:24:11.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-07-01T21:24:11.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.046 seconds
