[2025-06-26T23:11:10.223+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:11:10.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-26T23:11:10.237+0000] {logging_mixin.py:190} INFO - [2025-06-26T23:11:10.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:11:10.259+0000] {logging_mixin.py:190} INFO - [2025-06-26T23:11:10.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-26T23:11:10.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:11:10.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.128 seconds
[2025-06-26T23:11:40.416+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:11:40.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-26T23:11:40.421+0000] {logging_mixin.py:190} INFO - [2025-06-26T23:11:40.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:11:40.427+0000] {logging_mixin.py:190} INFO - [2025-06-26T23:11:40.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-26T23:11:40.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:11:40.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.049 seconds
[2025-06-26T23:12:11.077+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:12:11.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-26T23:12:11.081+0000] {logging_mixin.py:190} INFO - [2025-06-26T23:12:11.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:12:11.086+0000] {logging_mixin.py:190} INFO - [2025-06-26T23:12:11.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-26T23:12:11.087+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:12:11.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.045 seconds
[2025-06-26T23:12:41.522+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:12:41.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-26T23:12:41.533+0000] {logging_mixin.py:190} INFO - [2025-06-26T23:12:41.533+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:12:41.540+0000] {logging_mixin.py:190} INFO - [2025-06-26T23:12:41.538+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-26T23:12:41.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-26T23:12:41.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.065 seconds
